# Generated by Django 3.2.6 on 2021-08-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DHT22Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=3)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ts', models.DateTimeField()),
            ],
        ),
    ]
