# Generated by Django 3.2.6 on 2021-08-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dht', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DhtData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('ts', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dht_data',
                'managed': True,
            },
        ),
    ]
